### ISSUE TITLE
Webpack: Module parse failed. Unexpected token.

### ISSUE THREAD

**Issue by bibiseb** [matfish2/vue-tables-2#2]
- Vue.js version: 2.0
- consumed using: webpack
- FULL error message (including stack trace):
`ERROR in ./~/vue-tables-2/lib/template.jsx
Module parse failed: /Users/sebastien/Desktop/test/node_modules/vue-tables-2/lib/template.jsx Unexpected token (15:7)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (15:7)
    at Parser.pp$4.raise (/Users/sebastien/Desktop/test/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/sebastien/Desktop/test/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/sebastien/Desktop/test/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/sebastien/Desktop/test/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/sebastien/Desktop/test/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/sebastien/Desktop/test/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/sebastien/Desktop/test/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/sebastien/Desktop/test/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/Users/sebastien/Desktop/test/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseReturnStatement (/Users/sebastien/Desktop/test/node_modules/acorn/dist/acorn.js:839:33)
    at Parser.pp$1.parseStatement (/Users/sebastien/Desktop/test/node_modules/acorn/dist/acorn.js:699:34)
    at Parser.pp$1.parseBlock (/Users/sebastien/Desktop/test/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (/Users/sebastien/Desktop/test/node_modules/acorn/dist/acorn.js:2105:24)
    at Parser.pp$1.parseFunction (/Users/sebastien/Desktop/test/node_modules/acorn/dist/acorn.js:1065:10)
    at Parser.pp$3.parseExprAtom (/Users/sebastien/Desktop/test/node_modules/acorn/dist/acorn.js:1810:19)
    at Parser.pp$3.parseExprSubscripts (/Users/sebastien/Desktop/test/node_modules/acorn/dist/acorn.js:1715:21)
 @ ./~/vue-tables-2/lib/v-client-table.js 7:15-40
`
- steps for reproducing the issue: Use the vue-cli to create a webpack project, Follow all the instructions to setup the dependencies, simply import VueTable from 'vue-tables-2'

**Comment by matfish2** [comment]
Please READ THE DOCS. You need to use the jsx-transform

**Comment by bibiseb** [comment]
As I sais I followed all the instructions to setup the dependencies including babel-plugin-transform-vue-jsx and its own dependencies + the .babelrc conf...

**Comment by matfish2** [comment]
This is a question for the developer of  `babel-plugin-transform-vue-jsx`

**Comment by matfish2** [comment]
Issue reference: https://github.com/vuejs/babel-plugin-transform-vue-jsx/issues/25

**Comment by matfish2** [comment]
I have managed to compile using webpack with the following config:

```js
loaders: [{ test: /\.jsx?$/, loader: 'babel' }]
```

this target both `js` and `jsx` files

**Comment by BrianEstrada** [comment]
@matfish2 I got the tables installed but now it's giving me an error "options not defined" I pretty much followed the entire installation guide to a T so I'm not too sure what's going on.

**Comment by matfish2** [comment]
Can't really help you without seeing the relevant code

**Comment by sineld** [comment]
I am having the same issue:

```
[14:01:22] Starting 'webpack'...
{ [Error: ./~/vue-tables-2/lib/template.jsx
Module parse failed: /Users/sineld/Code/v3.yenibayi/node_modules/vue-tables-2/lib/template.jsx Unexpected token (15:7)
You may need an appropriate loader to handle this file type.
| var perPage = require('./template/per-page.jsx')(h, this);
|
| return <div class={"VueTables VueTables--" + this.source}>
|   <div class="row">
|     <div class="col-md-6">
 @ ./~/vue-tables-2/lib/v-server-table.js 6:15-40
 @ ./~/vue-tables-2/index.js
 @ ./resources/assets/js/webpack.js./~/vue-pagination-2/src/template.jsx
Module parse failed: /Users/sineld/Code/v3.yenibayi/node_modules/vue-pagination-2/src/template.jsx Unexpected token (8:8)
You may need an appropriate loader to handle this file type.
|   this.pages.map(function(page) {
|       items.push(
|         <li class="VuePagination__pagination-item"
|         class={this.activeClass(page)}>
|         <a href="javascript:void(0);"
```

**Comment by matfish2** [comment]
Read @eirabben comment on this [issue](vuejs/babel-plugin-transform-vue-jsx#25)
