### ISSUE TITLE
"SyntaxError: Invalid regular expression: /(+541)/: Nothing to repeat"

### ISSUE THREAD

**Issue by san4io** [matfish2/vue-tables-2#219]
- Vue.js version: 2.1.10
- consumed using: (browserify/webpack/rollup) webpack
- FULL error message (including stack trace):
```
SyntaxError: Invalid regular expression: /(+375)/: Nothing to repeat
    at RegExp (<anonymous>)
    at VueComponent.webpackJsonp../node_modules/vue-tables-2/compiled/filters/highlight-matches.js.module.exports (http://localhost/js/app.3e105a923e94c627e179.js:72970:11)
    at VueComponent.boundFn [as highlightMatch] (http://localhost/js/vendor.771f19899f223928bb42.js:171:14)
    at VueComponent.webpackJsonp../node_modules/vue-tables-2/compiled/methods/render.js.module.exports (http://localhost/js/app.3e105a923e94c627e179.js:73838:61)
    at Proxy.boundFn (http://localhost/js/vendor.771f19899f223928bb42.js:171:14)
    at Proxy.<anonymous> (http://localhost/js/app.3e105a923e94c627e179.js:75349:95)
    at Array.map (native)
    at Proxy.<anonymous> (http://localhost/js/app.3e105a923e94c627e179.js:75343:25)
    at Array.map (native)
    at webpackJsonp../node_modules/vue-tables-2/compiled/template/rows.js.module.exports (http://localhost/js/app.3e105a923e94c627e179.js:75326:10)
```
- steps for reproducing the issue:

When trying to search with special chars like +, I get error mentioned above.

**Comment by san4io** [comment]
Hello, 
This solution is failing with daterange column,
you should check if `s` is string or not object, and only if it is string then apply replacement.


TypeError: s.replace is not a function
    at escapeRegex (http://localhost/js/app.6394b89a8eae6f0116ee.js:73377:12)
    at VueComponent.webpackJsonp../node_modules/vue-tables-2/compiled/filters/highlight-matches.js.module.exports (http://localhost/js/app.6394b89a8eae6f0116ee.js:73359:28)
    at VueComponent.boundFn [as highlightMatch] (http://localhost/js/vendor.e222998c0fecfce77efc.js:185:14)
    at VueComponent.webpackJsonp../node_modules/vue-tables-2/compiled/methods/render.js.module.exports (http://localhost/js/app.6394b89a8eae6f0116ee.js:74277:61)
    at Proxy.boundFn (http://localhost/js/vendor.e222998c0fecfce77efc.js:185:14)
    at Proxy.<anonymous> (http://localhost/js/app.6394b89a8eae6f0116ee.js:75851:87)
    at Array.map (native)
    at Proxy.<anonymous> (http://localhost/js/app.6394b89a8eae6f0116ee.js:75845:21)
    at Array.map (native)
    at webpackJsonp../node_modules/vue-tables-2/compiled/template/rows.js.module.exports (http://localhost/js/app.6394b89a8eae6f0116ee.js:75828:8)
