### ISSUE TITLE
SyntaxError: Unexpected token: name (bus) during gulp --production

### ISSUE THREAD

**Issue by verwilst** [matfish2/vue-tables-2#34]
Using https://github.com/verwilst/laravel5-vuejs2 , i have a basic Laravel 5.3 with Vuejs 2 setup and laravel-elixir.

Gulp --production works fine then. 

Next, i run:

- npm install vue-tables-2
- npm install  babel-plugin-syntax-jsx  babel-plugin-transform-vue-jsx  babel-helper-vue-jsx-merge-props  --save-dev
- create .babelrc as documented.

As soon as i add var VueTables = require('vue-tables-2'); to my app.js, i get the following error when running gulp --production:

```
[15:36:03] Using gulpfile /app/gulpfile.js
[15:36:03] Starting 'all'...
[15:36:03] Starting 'sass'...
[15:36:03] Finished 'sass' after 755 ms
[15:36:03] Starting 'webpack'...
{ Error
    at new JS_Parse_Error (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)
    at semicolon (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2123:56)
    at simple_statement (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2314:73)
    at eval (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2183:19)
    at eval (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at block_ (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2429:20)
  message: '/app/app.js: SyntaxError: Unexpected token: name (bus)',
  fileName: '/app/app.js',
  lineNumber: 254,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)\n    at js_error (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)\n    at croak (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)\n    at token_error (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)\n    at unexpected (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)\n    at semicolon (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2123:56)\n    at simple_statement (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2314:73)\n    at eval (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2183:19)\n    at eval (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)\n    at block_ (eval at <anonymous> (/app/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2429:20)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-uglify' }





```

**Comment by matfish2** [comment]
Paste your `app.js`. According to the message the problem lies in line 254.

**Comment by verwilst** [comment]
The /app/app.js mentioned there doesn't exist. I think it's generated by gulp-uglify and removes as soon as the script fails. My 'actual' app.js is this:
import App from './pages/App.vue'
import FirstPage from './pages/FirstPage.vue'
import SecondPage from './pages/SecondPage.vue'

/**
 * First we will load all of this project's JavaScript dependencies which
 * include Vue and Vue Resource. This gives a great starting point for
 * building robust, powerful web applications using Vue and Laravel.
 */

require('./bootstrap');

/**
 * Next, we will create a fresh Vue application instance and attach it to
 * the body of the page. From here, you may begin adding components to
 * the application, or feel free to tweak this setup for your needs.
 */

var VueRouter = require('vue-router');
Vue.use(VueRouter);

var VueResource = require('vue-resource');
Vue.use(VueResource);

var VueTables = require('vue-tables-2')

Vue.http.options.root = '/api'

const routes = [
    { path: '/', component: FirstPage },
    { path: '/two', component: SecondPage }
  ]

const router = new VueRouter({
    mode: 'history',
    linkActiveClass: 'active',
    routes // short for routes: routes
})

const app = new Vue({
    el: '#app',
    template: '<App/>',
    components: { App },
    router
}).$mount('#app')

**Comment by verwilst** [comment]
It seems that it has something to do with node_modules being a symlink. On my production systems, node_modules is actually a symlink to ../../shared/node_modules. As soon as I remove the symlink, and copy ../../shared/node_modules to the wwwroot, gulp --production runs just fine.

**Comment by hong304** [comment]
I have the same problem when run gulp --production with requrie('vue-table-2');

my app.js just have one line 
require('vue-tables-2');


[16:31:35] Starting 'webpack'...
{ Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at expect_token (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2110:9)
    at expect (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2113:36)
    at eval (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2686:13)
    at eval (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at expr_atom (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2616:35)
    at maybe_unary (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
  message: '/Users/hilton/Code/ching/app.js: SyntaxError: Unexpected token punc «,», expected punc «:»',
  fileName: '/Users/hilton/Code/ching/app.js',
  lineNumber: 2090,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)\n    at js_error (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)\n    at croak (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)\n    at token_error (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)\n    at expect_token (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2110:9)\n    at expect (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2113:36)\n    at eval (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2686:13)\n    at eval (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)\n    at expr_atom (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2616:35)\n    at maybe_unary (eval at <anonymous> (/Users/hilton/Code/ching/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-uglify' }

**Comment by matfish2** [comment]
The index.js file had some ES6 in it. Please try again.
