### ISSUE TITLE
Illegal mix of collations for operation 'like' while searching

### ISSUE THREAD

**Issue by thanosalexander** [matfish2/vue-tables-2#425]
I use the server table with the laravel implementation. All working perfect except the searching with foreign characters eg Greek (βρ)

- Vue.js version: 2.5.7
- consumed using webpack

- exception 
```
"Illuminate\Database\QueryException"
```
- file
```
"/home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
```
- line
```
644
```

- message
```
"SQLSTATE[HY000]: General error: 1271 Illegal mix of collations for operation 'like' (SQL: select * from `` where (`id` LIKE %β% or `name` LIKE %β% or `created_at` LIKE %β% or `dimensions` LIKE %β%) and `banners`.`deleted_at` is null)"
```

- FULL error message (including stack trace):
```
#0 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))\n
#1 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))\n
#2 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1748): Illuminate\Database\Connection->select('select count(*)...', Array, true)\n
#3 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1733): Illuminate\Database\Query\Builder->runSelect()\n
#4 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2080): Illuminate\Database\Query\Builder->get(Array)\n
#5 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2008): Illuminate\Database\Query\Builder->aggregate('count', Array)\n
#6 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1281): Illuminate\Database\Query\Builder->count()\n
#7 /home/webdev/Projects/demo/app/Repositories/BannerRepository.php(58): Illuminate\Database\Eloquent\Builder->__call('count', Array)\n
#8 /home/webdev/Projects/demo/app/Http/Controllers/BannerController.php(75): App\Repositories\BannerRepository->get(Array)\n
#9 [internal function]: App\Http\Controllers\BannerController->fetchAdvertised(Object(Illuminate\Http\Request))\n
#10 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)\n
#11 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('fetchAdvertised', Array)\n
#12 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\BannerController), 'fetchAdvertised')\n
#13 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()\n
#14 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\Routing\Route->run()\n
#15 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#16 /home/webdev/Projects/demo/app/Http/Middleware/CompressHTML.php(34): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#17 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\Http\Middleware\CompressHTML->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#18 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#19 /home/webdev/Projects/demo/app/Http/Middleware/LanguageMiddleware.php(72): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#20 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\Http\Middleware\LanguageMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#21 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#22 /home/webdev/Projects/demo/app/Http/Middleware/CorsMiddleware.php(20): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#23 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\Http\Middleware\CorsMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#24 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#25 /home/webdev/Projects/demo/app/Http/Middleware/CurrencyMiddleware.php(52): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#26 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\Http\Middleware\CurrencyMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#27 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#28 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#29 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#30 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#31 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#32 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#33 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#34 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#35 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\AuthenticateSession->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#36 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#37 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#38 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#39 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#40 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#41 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#42 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#43 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#44 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#45 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#46 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#47 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#48 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#49 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#50 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#51 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#52 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#53 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(661): Illuminate\Pipeline\Pipeline->then(Object(Closure))\n
#54 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))\n
#55 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(602): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))\n
#56 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(591): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))\n
#57 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))\n
#58 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))\n
#59 /home/webdev/Projects/demo/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#60 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#61 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#62 /home/webdev/Projects/demo/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#63 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#64 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#65 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#66 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#67 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#68 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#69 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#70 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#71 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#72 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#73 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#74 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#75 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))\n
#76 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))\n
#77 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))\n
#78 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))\n
#79 /home/webdev/Projects/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))\n
#80 /home/webdev/Projects/demo/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))\n
#81 {main}
```

- relevant code:
```
public function get($fields) {

        extract(request()->only(['query', 'limit', 'page', 'orderBy', 'ascending', 'byColumn']));

        /** @var Builder $data */
        $data = (new Banner())->with('categories', 'user.banners', 'photo');

        if (isset($query) && $query) {

            $data = $byColumn==1?$this->filterByColumn($data, $query):

            $this->filter($data, $query, $fields);
        }

        $count = $data->count();

        $data->limit($limit)
            ->skip($limit * ($page-1));

        if (isset($orderBy)):
            $direction = $ascending==1?"ASC":"DESC";
            $data->orderBy($orderBy,$direction);
        endif;

        $results = $data->get()->toArray();

        return [
            'data'=>$results,
            'count'=>$count
        ];

    }

    protected function filterByColumn($data, $query) {
        foreach ($query as $field=>$query):

            if (!$query) continue;

            if (is_string($query)) {
                $data->where($field,'LIKE',"%{$query}%");
            } else {

                $start = Carbon::createFromFormat('Y-m-d',$query['start'])->startOfDay();
                $end = Carbon::createFromFormat('Y-m-d',$query['end'])->endOfDay();

                $data->whereBetween($field,[$start, $end]);
            }
        endforeach;

        return $data;
    }

    protected function filter($data, $query, $fields) {
        foreach ($fields as $index=>$field):
            $method = $index?"orWhere":"where";
            $data->{$method}($field,'LIKE',"%{$query}%");
        endforeach;

        return $data;
    }
```
- steps for reproducing the issue: search with an other character (eg greek   βρ)

**Comment by matfish2** [comment]
According to [this](https://stackoverflow.com/questions/18629094/illegal-mix-of-collations-for-operation-like-while-searching-with-ignited-data), `DATETIME` fields in MySQL cannot be searched using the LIKE operator. You need to declare `created_at` and any other date fields using the `dateColumns` option. This will replace the text filter with a dedicated date range picker (requires [Daterangepicker](https://github.com/dangrossman/bootstrap-daterangepicker)). The request in turn will reflect this change and the issue should be resolved.

**Comment by thanosalexander** [comment]
I have it already in dateColumns but i realized something else.
Of course the error is that mysql not search with LIKE in timestamps..
I found that something's going wrong in filter function(the same too maybe for filterByColumn function).
if i put this for example

```
 protected function filter($data, $query, $fields) {
        foreach ($fields as $index=>$field):
            if(!in_array($field,['created_at','deleted_at'])) //Or maybe any dateColumn here
            {
                  $method = $index?"orWhere":"where";
                  $data->{$method}($field,'LIKE',"%{$query}%");
            }
        endforeach;

        return $data;
    }
```
i managed to make the search..
Maybe this is not an elegant solution but it works like this

**Comment by matfish2** [comment]
I just realized that you are using a single filter (`filterByColumn: false`). In this scenario the method just combs through all the columns using the `LIKE` operator to find a match. Maybe I can add a `dateColumns` parameter to the server class, to handle search in dateColumns. Another, maybe better, solution can be to cast all fields to `VARCHAR`.

**Comment by thanosalexander** [comment]
I agree! sure ```VARCHAR``` will be ok too.. I was thinking to tell you about ddateColumns parameter too but you suggest it first!
