### ISSUE TITLE
JSX compiling issue

### ISSUE THREAD

**Issue by CoolGoose** [matfish2/vue-tables-2#69]
- Vue.js version: 2.1.10
- consumed using: browserify
- FULL error message (including stack trace):
```bash
events.js:141
      throw er; // Unhandled 'error' event
      ^

SyntaxError: X:/Projects/Teamspeak/dev-www/www_sources/dev-myts-admin.int.teamspeak.com/public/assets/node_modules/vue-tables-2/lib/template.jsx: Unexpected token (15:7)
  13 | var perPage = require('./template/per-page.jsx')(h, this);
  14 |
> 15 | return <div class={"VueTables VueTables--" + this.source}>
     |        ^
  16 |   <div class="row">
  17 |     <div class="col-md-6">
  18 |       {normalFilter}
    at Parser.pp$5.raise (X:\Projects\Teamspeak\dev-www\www_sources\dev-myts-admin.int.teamspeak.com\public\assets\node_modules\babylon\lib\index.js:4333:13)
    at Parser.pp.unexpected (X:\Projects\Teamspeak\dev-www\www_sources\dev-myts-admin.int.teamspeak.com\public\assets\node_modules\babylon\lib\index.js:1705:8)
    at Parser.pp$3.parseExprAtom (X:\Projects\Teamspeak\dev-www\www_sources\dev-myts-admin.int.teamspeak.com\public\assets\node_modules\babylon\lib\index.js:3670:12)
    at Parser.pp$3.parseExprSubscripts (X:\Projects\Teamspeak\dev-www\www_sources\dev-myts-admin.int.teamspeak.com\public\assets\node_modules\babylon\lib\index.js:3414:19)
    at Parser.pp$3.parseMaybeUnary (X:\Projects\Teamspeak\dev-www\www_sources\dev-myts-admin.int.teamspeak.com\public\assets\node_modules\babylon\lib\index.js:3394:19)
    at Parser.pp$3.parseExprOps (X:\Projects\Teamspeak\dev-www\www_sources\dev-myts-admin.int.teamspeak.com\public\assets\node_modules\babylon\lib\index.js:3324:19)
    at Parser.pp$3.parseMaybeConditional (X:\Projects\Teamspeak\dev-www\www_sources\dev-myts-admin.int.teamspeak.com\public\assets\node_modules\babylon\lib\index.js:3301:19)
    at Parser.pp$3.parseMaybeAssign (X:\Projects\Teamspeak\dev-www\www_sources\dev-myts-admin.int.teamspeak.com\public\assets\node_modules\babylon\lib\index.js:3264:19)
    at Parser.pp$3.parseExpression (X:\Projects\Teamspeak\dev-www\www_sources\dev-myts-admin.int.teamspeak.com\public\assets\node_modules\babylon\lib\index.js:3226:19)
    at Parser.pp$1.parseReturnStatement (X:\Projects\Teamspeak\dev-www\www_sources\dev-myts-admin.int.teamspeak.com\public\assets\node_modules\babylon\lib\index.js:2024:26)
```
- relevant code:
```js
"babelify",
{
     global: true,
     ignore: /node_modules(?!\/(vue-tables-2|vue-pagination-2))/,
     presets: ["es2015"],
                  plugins: ["transform-vue-jsx"]
     }
)
```
- steps for reproducing the issue:
Just using 
```js
"browserify": {
    "transform": [
      "babelify"
    ]
  },
```
Isn't enough in the package.json 
You need to apply both the preset and the plugin for the package.json to work, or to apply the global transformation like i did above.

The problem remains that for some reason it still doesn't like the JSX. Any tips regarding this ?

**Comment by karneaud** [comment]
+1

got this same response

**Comment by zcwilt** [comment]
just a note. 

For laravel(5.3) elixir I had to create a `webpack.config.js` containing 

```
Elixir.webpack.mergeConfig({
    module: {
        loaders: [
            {
                test: /\.jsx?$/,
                loader: 'babel',
                exclude: /node_modules(?!\/(vue-tables-2|vue-pagination-2))/
            },
        ]
    }
})

```

There is also a lot of stuff you need to `npm install` to get babel working correctly for laravel. 

I can share more of my `package.json` `bootstrap.js` if anyones interested.

**Comment by CoolGoose** [comment]
@zcwilt in theory I have the same setup with babelify. Maybe it's not working with babelify ?

**Comment by zcwilt** [comment]
so I found that the main problem with getting stuff working was making sure I had all the correct tooling in my `packages.json`

@CoolGoose I've never used babelify, so don't know. 

Here is my `package.json`

```
{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "axios": "^0.15.3",
    "babel": "^6.5.2",
    "babel-cli": "^6.22.2",
    "babel-helper-vue-jsx-merge-props": "^2.0.2",
    "babel-loader": "^6.2.10",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-vue-jsx": "^3.3.0",
    "babel-preset-es2015": "^6.22.0",
    "bootstrap-sass": "^3.3.7",
    "gulp": "^3.9.1",
    "jquery": "^3.1.0",
    "laravel-elixir": "^6.0.0-14",
    "laravel-elixir-vue-2": "^0.2.0",
    "laravel-elixir-webpack-official": "^1.0.2",
    "lodash": "^4.16.2",
    "vue": "^2.0.1",
    "vue-resource": "^1.0.3",
    "vue-tables-2": "^0.3.0"
  }
}

```


and my `.babelrc`

```
{
  "presets": ["es2015"],
  "plugins": ["transform-vue-jsx"]
}
```

**Comment by CoolGoose** [comment]
@zcwilt it seems that .babelrc is enough .. i could remove the extra code from babelify and it now compiles correctly.

**Comment by CoolGoose** [comment]
And here's the pull request https://github.com/matfish2/vue-tables-2/pull/72
