### ISSUE TITLE
Heading render from JSX fails when `filterByColumn: true`

### ISSUE THREAD

**Issue by awmottaz** [matfish2/vue-tables-2#78]
When using JSX to render a heading, filtering by that column produces an error. I believe this fails at the `column:that.getHeading(column)})` function call in
- `list-filter.jsx`
- `text-filter.jsx`
- `date-filter.jsx`

(This may also be the culprit in Issue #66)

- Vue.js version: 2.1.10
- consumed using: webpack
- FULL error message (including stack trace):

```
[Vue warn]: Error when rendering component <client-table>: 
warn @ vue.common.js?e881:521
Vue._render @ vue.common.js?e881:2223
updateComponent @ vue.common.js?e881:2609
get @ vue.common.js?e881:2934
Watcher @ vue.common.js?e881:2926
Vue._mount @ vue.common.js?e881:2608
Vue$3.$mount @ vue.common.js?e881:6178
Vue$3.$mount @ vue.common.js?e881:8549
init @ vue.common.js?e881:1740
createComponent @ vue.common.js?e881:4174
createElm @ vue.common.js?e881:4117
patch @ vue.common.js?e881:4569
Vue._update @ vue.common.js?e881:2635
updateComponent @ vue.common.js?e881:2609
get @ vue.common.js?e881:2934
Watcher @ vue.common.js?e881:2926
Vue._mount @ vue.common.js?e881:2608
Vue$3.$mount @ vue.common.js?e881:6178
Vue$3.$mount @ vue.common.js?e881:8549
init @ vue.common.js?e881:1740
createComponent @ vue.common.js?e881:4174
createElm @ vue.common.js?e881:4117
createChildren @ vue.common.js?e881:4242
createElm @ vue.common.js?e881:4150
updateChildren @ vue.common.js?e881:4387
patchVnode @ vue.common.js?e881:4450
patch @ vue.common.js?e881:4574
Vue._update @ vue.common.js?e881:2642
updateComponent @ vue.common.js?e881:2609
get @ vue.common.js?e881:2934
run @ vue.common.js?e881:3003
flushSchedulerQueue @ vue.common.js?e881:2807
(anonymous) @ vue.common.js?e881:473
nextTickHandler @ vue.common.js?e881:422


vue.common.js?e881:435 TypeError: h is not a function
    at Object.exports.default [as items] (eval at <anonymous> (http://amottaz.jumptechtest.com/app.js:2450:1), <anonymous>:8:10)
    at VueComponent.module.exports (eval at <anonymous> (http://amottaz.jumptechtest.com/app.js:2002:1), <anonymous>:15:88)
    at Proxy.boundFn (eval at <anonymous> (http://amottaz.jumptechtest.com/app.js:729:1), <anonymous>:126:14)
    at eval (eval at <anonymous> (http://amottaz.jumptechtest.com/app.js:2436:1), <anonymous>:18:84)
    at eval (eval at <anonymous> (http://amottaz.jumptechtest.com/app.js:2366:1), <anonymous>:28:20)
    at Array.map (native)
    at module.exports (eval at <anonymous> (http://amottaz.jumptechtest.com/app.js:2366:1), <anonymous>:22:19)
    at Proxy.eval (eval at <anonymous> (http://amottaz.jumptechtest.com/app.js:2359:1), <anonymous>:8:47)
    at VueComponent.Vue._render (eval at <anonymous> (http://amottaz.jumptechtest.com/app.js:729:1), <anonymous>:2216:22)
    at VueComponent.updateComponent (eval at <anonymous> (http://amottaz.jumptechtest.com/app.js:729:1), <anonymous>:2609:21)
```
- relevant code:

**foo.jsx**

```jsx
export default function(h) { return <span>Foo</span> }
```

**App.vue**

```javascript
import foo from 'template/foo.jsx'

options: {
  filterByColumn: true,
  filterable: ['foo'],
  headings: {
    foo
  }
}
```

- steps for reproducing the issue: Use `<v-client-table>` with options above.

**Comment by matfish2** [comment]
I don't think it has anything to do with `filterByColumn`, as this is not a run-time error, but a compilation one. Does the error disappear when you remove `filterByColumn:true`? I suggest you look into the build process configuration.

**Comment by awmottaz** [comment]
The error disappeared either when removing `filterByColumn: true`, or even just excluding `foo` from the `filterable` array.
