### ISSUE TITLE
`Cannot read property 'runtime' of undefined` in unit tests

### ISSUE THREAD

**Issue by VladZen** [matfish2/vue-tables-2#832]
I have a problem in my unit tests only:
```
TypeError: Cannot read property 'runtime' of undefined
at ModuleCollection.unregister (node_modules/vuex/dist/vuex.common.js:219:28)
      at Store.unregisterModule (node_modules/vuex/dist/vuex.common.js:512:17)
      at Object.<anonymous>.module.exports (node_modules/vue-tables-2/compiled/state/register-module.js:19:17)
      at Object.<anonymous>.module.exports (node_modules/vue-tables-2/compiled/mixins/created.js:9:5)
      at VueComponent.created (node_modules/vue-tables-2/compiled/v-server-table.js:65:7)
```

After some research I figured out that users are stuck with the same problem using SSR. For example, https://github.com/vuejs/vue-ssr-docs/issues/137#issue-260312666 . Diving deeper I discovered that It also can be rooted from the dynamic registration of the vuex module inside `created` hook instead of `beforeCreate`

Possible solutions:
1. https://github.com/matfish2/vue-tables-2/blob/46e4da009add5d3631cf6741d1ada6011619e118/lib/state/register-module.js#L12
I suppose it could be better to check out the existence of the registered module using https://vuex.vuejs.org/api/#hasmodule

2. Move the registration of the module inside `beforeCreate` instead of `created`

These all things are just assumptions. I will try to test them and let you know if I come up with something.

**Comment by VladZen** [comment]
I was wrong and my error rooted from another reason. But still [this](https://github.com/matfish2/vue-tables-2/blob/46e4da009add5d3631cf6741d1ada6011619e118/lib/state/register-module.js#L12) can be changed to https://vuex.vuejs.org/api/#hasmodule . This functionality has been implemented recently
https://github.com/vuejs/vuex/pull/834
